name: Docker Image Scan Demo

on:
  push:
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:8})
            
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: purpledobie/hello-tomcat:latest,purpledobie/hello-tomcat:${{steps.vars.outputs.tag}}
               
    - name: Snyk container scan
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        DEBUG: true
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: purpledobie/hello-tomcat:${{steps.vars.outputs.tag}}
        args: --file=Dockerfile  
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif
